### ISSUE TITLE
Make use of SSD HD

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#168]
Here is my idea for a low invasive change.

1. Define an optional variable: SCIPION_SSD_FOLDER ?
2. When creating the Tmp folder of the protocol, evaluate the new variable.

3. If defined and is a folder:
      Create "unique" folder inside SCIPION_SSD_FOLDER --> `<projectname>_<protId>`?
      Link the Tmp folder at the protocol folder to the SSD newly created folder
      When removing "cleaning" the  tmp, remove the linked folder in the SSD path
4. Else, current behaviour.

I believe this can be done quickly without much risk and still be useful.

THoughts, @delarosatrevin , @dmaluenda ,  @azazellochg , @fonsecareyna82 , @JorMaister , @rmarabini , @cossorzano ?

**Comment by delarosatrevin** [comment]
Sounds really good! I have been thinking about this idea for a while but never found time to push it. As you said, it should be low-risk and not very complicated to implement. 

I will only propose to change the variable name to SCIPION_SCRATCH or something shorter, preferably avoiding SSD, since it is hardware and not relevant. The Tmp could also be mounted in ram filesystem (e. g tmpfs)

**Comment by pconesa** [comment]
Thanks @delarosatrevin , much better SCIPION_SCRATCH (so be it, ;-))

**Comment by JorMaister** [comment]
Absolutely in agreement with the SSD usage proposed, @pconesa, and also with the hardware independent name proposed by @delarosatrevin, SCIPION_SCRATCH.

**Comment by cossorzano** [comment]
I think this is a step forward (specially within protocols), but it does not fully solve the problem of speed in streaming (between protocols). For instance, Protocol1 produces an output micrograph. As Protocol1 has finished with Mic1, it moves it to extra. Now, Protocol2 needs to do something with Mic1 (which is no longer at the scratch, but at the standard disk). Same for Protocol 3 and Protocol4. Eventually, all the protocols in the workflow have finished with Mic1, then that is the right time to move to standard disk.

How would you solve this problem?

**Comment by delarosatrevin** [comment]
@cossorzano Maybe this can be a second layer on top of the Tmp management in the scratch space. It could be a delayed clean up of items and a unique tmp name, so protocol 2 that use an item can check if it is already in the tmp. Maybe this would be better centralize somewhere to manage this tmp management for storing, retrieval and clean-up.

**Comment by azazellochg** [comment]
That's a good idea. SSDs are very good at reading data. I would suggest to have this var in scipion.conf and also it should be possible to use it in hosts.conf (when the value is not known in advance and can be set e.g. SCRATCH_DIR="/ssd/${SLURM_JOB_USER}-${SLURM_JOBID}")
I agree with @cossorzano that this will not speed up the chain of protocols that use the same data. Relion has keep-scratch option for this cases.

**Comment by dmaluenda** [comment]
Hi there, I totally agree on you all.

We may start with this first approach, speeding up the protocol runs, and let's move to a more sophisticated one afterwards.

Continuing with the brain storming on an efficient scratch usage, the typical problem on them is their size variability, I mean one can have a SSD of a couple of terabytes when other can use a RAM disk of a few gigabytes. This introduce complexity in our approach. I don't want say that SCRATCH_DIR is a bad idea, I totally agree on that, but I think we should consider this variability.

I think that making links from scratch/protocol/tmp to hard/protocol/tmp is a good approach, but also 'extra' folders should enter in that equation since the cross-talk between protocols is by means of the extra files. Therefore, the magic is to decide when can be considered that a file/folder is ready to be definitively moved to the hard-drive.

**Comment by azazellochg** [comment]
We should also consider #131 here

**Comment by pconesa** [comment]
Involving extra, brings the problem of space. I know we are not covering all with this but also, @rmarabini did some time ago some tests and prooved that builtin "Linux read cache" covers for recent I/O activity. 

I'd go for this quick and simple approach since mos of us sees it positive,and see, then what else can be done.
