### ISSUE TITLE
VolumeMask wrong default viewer

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#194]
I think I saw some commits about this, but currently the default viewer is still bshow, despite that I have:
VIEWERS = {"Volume":["pwem.viewers.viewers_data.DataViewer"]} in config

**Comment by pconesa** [comment]
Thanks Gregory, This was fixed here,
https://github.com/scipion-em/scipion-app/blob/devel/scipion/__main__.py#L243

But since you have it defined, is taking you definition that is partial.
Maybe we can find a way treat each item separately but for now is all or
nothing.

You can update you variable in the config or remove it.

**Comment by azazellochg** [comment]
Oh, I didn't know that. So I just need to remove my definition and it
should work
